/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.edu.irati.tads.view;

/**
 *
 * @author felipe
 */
public class TelaInicialGUI extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialGUI
     */
    public TelaInicialGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuGerenciarCliente = new javax.swing.JMenu();
        jMenuGerenciarCompra = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SisCoxinha");
        setResizable(false);

        jMenuGerenciarCliente.setText("Gerenciar Clientes");
        jMenuGerenciarCliente.setToolTipText("");
        jMenuGerenciarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuGerenciarClienteMouseClicked(evt);
            }
        });
        jMenuGerenciarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerenciarClienteActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuGerenciarCliente);

        jMenuGerenciarCompra.setText("Lançar Compra");
        jMenuGerenciarCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuGerenciarCompraMouseClicked(evt);
            }
        });
        jMenuGerenciarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuGerenciarCompraActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuGerenciarCompra);

        jMenu1.setText("Gerenciar Compra");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuGerenciarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerenciarClienteActionPerformed
        GerenciarClienteGUI gerenciarClienteGUI = new GerenciarClienteGUI();
        gerenciarClienteGUI.setVisible(true);
    }//GEN-LAST:event_jMenuGerenciarClienteActionPerformed

    private void jMenuGerenciarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuGerenciarCompraActionPerformed
        
    }//GEN-LAST:event_jMenuGerenciarCompraActionPerformed

    private void jMenuGerenciarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuGerenciarClienteMouseClicked
        GerenciarClienteGUI gerenciarClienteGUI = new GerenciarClienteGUI();
        gerenciarClienteGUI.setVisible(true);
    }//GEN-LAST:event_jMenuGerenciarClienteMouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        GerenciarCompraGUI gerenciarCompraGUI = new GerenciarCompraGUI();
        gerenciarCompraGUI.setVisible(true);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenuGerenciarCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuGerenciarCompraMouseClicked
        LancarCompraGUI lancarCompraGUI = new LancarCompraGUI();
        lancarCompraGUI.setVisible(true);
    }//GEN-LAST:event_jMenuGerenciarCompraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuGerenciarCliente;
    private javax.swing.JMenu jMenuGerenciarCompra;
    // End of variables declaration//GEN-END:variables
}
